//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthwindMembershipApp.UI.Web.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public Page()
        {
            this.Page1 = new HashSet<Page>();
            this.Roles = new HashSet<Role>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string TitleInEnglish { get; set; }
        public string Action { get; set; }
        public string Controller { get; set; }
        public Nullable<int> ParentPageId { get; set; }
        public Nullable<int> RowOrder { get; set; }
        public Nullable<bool> IsMenuPage { get; set; }
    
        public virtual ICollection<Page> Page1 { get; set; }
        public virtual Page Page2 { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
    }
}
