//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthwindMembershipApp.UI.Web.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.Users = new HashSet<User>();
            this.Pages = new HashSet<Page>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> RoleLevel { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<Page> Pages { get; set; }
    }
}
